#!/bin/bash
## check on the process age and kill if running for too long
PROCESS="sleep"
LOGAN="10800"
if pgrep "$PROCESS" ; then
  PID=$(pgrep "$PROCESS")
  AGE=$(ps -o etimes= -p "$PID")
  #Show results:
  echo PID:"$PID", AGE:"$AGE"
  if [[ "$AGE" -gt "$LOGAN" ]]
    then
    kill "$PID"
  else
    exit 0
  fi
else
  exit 0
fi
